name: Auto Deploy Site

on:
  # Run after the summary workflow completes successfully
  workflow_run:
    workflows: ["Summarize Executive Orders"]
    types:
      - completed
  
  # Allow manual triggering for testing
  workflow_dispatch:

jobs:
  deploy-site:
    runs-on: ubuntu-latest
    # Only run if the summarize workflow succeeded or if manually triggered
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history for proper git operations
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Build
        env:
          NODE_ENV: production
          # Prevent CI from treating warnings as errors
          CI: 'false'
        run: npm run build
        
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build
          token: ${{ secrets.PAT }}
          branch: gh-pages
          clean: true