name: Auto Deploy Site

on:
  # Run after the summary workflow completes successfully
  workflow_run:
    workflows: ["Summarize Executive Orders"]
    types:
      - completed
  
  # Allow manual triggering for testing
  workflow_dispatch:

jobs:
  deploy-site:
    runs-on: ubuntu-latest
    # Only run if the summarize workflow succeeded or if manually triggered
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history for proper git operations
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Build and deploy
        env:
          NODE_ENV: production
          # Use your GitHub token for deployment
          GH_TOKEN: ${{ secrets.PAT }}
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          npm run deploy